sudo: required

language: c

services:
  - docker

script:
  - docker build -t fpinsight/stack-build .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push fpinsight/stack-build;
    fi
